// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_peri_bind module generated by `tlgen.py` tool for assertions
module xbar_peri_bind;
`ifndef GATE_LEVEL
  // Host interfaces
  bind xbar_peri tlul_assert #(.EndpointType("Device")) tlul_assert_host_ibex_lsu (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_ibex_lsu_i),
    .d2h    (tl_ibex_lsu_o)
  );

  // Device interfaces
  bind xbar_peri tlul_assert #(.EndpointType("Host")) tlul_assert_device_sram (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_sram_o),
    .d2h    (tl_sram_i)
  );
  bind xbar_peri tlul_assert #(.EndpointType("Host")) tlul_assert_device_uart (
    .clk_i  (clk_i),
    .rst_ni (rst_ni),
    .h2d    (tl_uart_o),
    .d2h    (tl_uart_i)
  );
`endif
endmodule
