// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_env_pkg__params generated by `tlgen.py` tool


// List of Xbar device memory map
tl_device_t xbar_devices[$] = '{
    '{"sram", '{
        '{32'h00100000, 32'h0011ffff}
    }},
    '{"uart", '{
        '{32'h80000000, 32'h80000fff}
}}};

  // List of Xbar hosts
tl_host_t xbar_hosts[$] = '{
    '{"ibex_lsu", 0, '{
        "sram",
        "uart"}}
};
