# Licenses and Copyright for Generated hardware components

version = 1

[[annotations]]
path = [
    "ip_autogen/alert_handler/**",
    "ip_autogen/clkmgr/**",
    "ip_autogen/gpio/**",
    "ip_autogen/pwrmgr/**",
    "ip_autogen/rstmgr/**",
    "ip_autogen/rv_plic/**",
]
SPDX-FileCopyrightText = "lowRISC Contributors (OpenTitan project)."
SPDX-License-Identifier = "Apache-2.0"
